version: '3'

# Specify the services to run
services:

# Backend services to run
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    networks:
      - my-network
    volumes:
      - ./backend:/app
    stdin_open: true
    tty: true
    image: backend-image:v1.0.0

# Frontend services to run
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - my-network
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true
    image: backend-image:v1.0.0


# Mongodb services to run
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - my-network
    volumes:
      - mongodb_data:/data/db

# Network 
networks:
  my-network:
    driver: bridge

# Specify volume 
volumes:
  mongodb_data:

# Verify image sizes:
#
# To check the size of the built images, run the following command in the terminal:
#
#     docker images
#
# This will display a list of all Docker images on your system, including their sizes.
# Verify the sizes of the backend-image and frontend-image to ensure they meet your requirements.

    