version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    networks:
      - my-network
    volumes:
      - ./backend:/app
    stdin_open: true
    tty: true


  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - my-network
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true


  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - my-network
    volumes:
      - mongodb_data:/data/db

networks:
  my-network:
    driver: bridge

volumes:
  mongodb_data:

    