---
- name: sample playbook
  hosts: all
  become: yes
  
  vars:
      ansible_python_interpreter: /usr/bin/python3  # Specify Python 3 interpreter path

  roles:
    - ansible-automation

  tasks:
  - name: install apache
    yum:
      name: ntp
      state: latest



