---
- name: Install 'Docker SDK for Python' using pip
  pip:
    name: docker
    state: present
    executable: pip3  # Use pip3 executable for Python 3
  become: true

- name: Update pip
  raw: pip3 install --upgrade pip
  become: true

- name: Install 'setuptools_rust' package
  raw: pip3 install setuptools_rust
  become: true

- name: Retry installing 'Docker SDK for Python' (docker-compose)
  raw: pip3 install docker-compose
  become: true

- name: Add Docker official repository
  yum_repository:
    name: docker-ce
    description: Docker CE Repository
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    state: present
  become: true

- name: Install Docker packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  become: true

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: true

- name: Copy Docker Compose file to the VM
  copy:
    src: docker-compose.yml
    dest: /home/vagrant/YoloApp/docker-compose.yml
  become: true

- name: Ensure correct permissions for Docker Compose file
  file:
    path: /home/vagrant/YoloApp/docker-compose.yml
    mode: "0644"
    owner: vagrant
    group: vagrant
  become: true

- name: Run Docker Compose pull
  command: /usr/local/bin/docker-compose -f /home/vagrant/YoloApp/docker-compose.yml pull -d
  become: true


- name: Run Docker Compose
  command: docker compose up -d 
  args:
    chdir: /home/vagrant/YoloApp/
  become: true















